In [ ]:
import numpy as np
from glaciation_time_estimator.auxiliary_func.chunking_data import ChunkLoader

:

Loaded config from /wolke_scratch/dnikolo/Glaciation_time_estimator/configs/debug/debug.yaml

In [10]:
import pandas as pd

In [12]:
chunker_weighted = ChunkLoader([2008],config_fp="/wolke_scratch/dnikolo/Glaciation_time_estimator/configs/debug/debug.yaml")
chunker_non_weighted = ChunkLoader([2008],config_fp="/wolke_scratch/dnikolo/Glaciation_time_estimator/configs/debug/debug_non_weighted.yaml")

Loaded config from /wolke_scratch/dnikolo/Glaciation_time_estimator/configs/debug/debug.yaml
Loaded config from /wolke_scratch/dnikolo/Glaciation_time_estimator/configs/debug/debug_non_weighted.yaml

In [13]:
clouds_weighted = chunker_weighted.cloud_chunk
clouds_non_weighted = chunker_non_weighted.cloud_chunk

In [14]:
def occ_rate(cloud_chunk):
    return pd.pivot_table(cloud_chunk[cloud_chunk.max_water_frac > 0.4],values='is_glaciating' ,index=["Hemisphere"], columns=["min_temp"], aggfunc='mean')

In [15]:
table_weighted = occ_rate(clouds_weighted)
table_non_weighted = occ_rate(clouds_non_weighted)

In [18]:
table_non_weighted

min_temp         -36       -30       -24       -18       -12  -6
Hemisphere
North       0.107984  0.069344  0.038704  0.020791  0.005093  0.0
South       0.103279  0.043647  0.022769  0.014354  0.004554  0.0

In [17]:
table_weighted

min_temp         -36       -30       -24       -18       -12  -6
Hemisphere
North       0.107984  0.069344  0.038704  0.020791  0.005093  0.0
South       0.103279  0.043647  0.022769  0.014354  0.004554  0.0